export const FETCH_CANDIDATE_BEGIN = 'FETCH_CANDIDATE_BEGIN';
export const FETCH_CANDIDATE_SUCCESS = 'FETCH_CANDIDATE_SUCCESS';
export const FETCH_CANDIDATE_FAILURE = 'FETCH_CANDIDATE_FAILURE';

export const UPDATE_CANDIDADTE_BEGIN = 'UPDATE_CANDIDADTE_BEGIN';
export const UPDATE_CANDIDATE_SUCCESS = 'FETCH_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_FAILURE = 'FETCH_CANDIDATE_FAILURE';

